# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details

version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-ecs: circleci/aws-ecs@0.0.10

jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      SBT_VERSION: 1.3.13

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run: cat /dev/null | sbt test:test

  create_and_push_img:
    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      SBT_VERSION: 1.3.13

    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run:
          name: install sbt
          command: |
            sudo apt update && sudo apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            sudo dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb

      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: create dist zip file
          command: cat /dev/null | sbt clean update dist
      - run:
          name: unzip
          command: unzip target/universal/mazesite-1.0-SNAPSHOT.zip

      - aws-ecr/build-and-push-image:
          repo: mazegen
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: ACCESS_KEY_ID_IAM_ADMIN
          aws-secret-access-key: SECRET_ACCESS_KEY_IAM_ADMIN
          profile-name: IAMAdmin
          region: AWS_REGION
      - aws-ecs/update-service:
          aws-access-key-id: ACCESS_KEY_ID_IAM_ADMIN
          aws-secret-access-key: SECRET_ACCESS_KEY_IAM_ADMIN
          aws-region: AWS_REGION
          family: mazeGen-task
          cluster-name: mazeGen-cluster
          #container-image-name-updates: "container=${ECS_SERVICE_NAME},image-and-tag=${FULL_IMAGE_NAME}"
          verify-revision-is-deployed: true

workflows:
  build_and_push_image:
    jobs:
      #- test
      - create_and_push_img:
          context: mazegen-aws
#          requires:
#            - test
#          filters:
#            branches:
#              only: master




