# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      SBT_VERSION: 1.3.13

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run: cat /dev/null | sbt test:test

  create_and_push_img:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      SBT_VERSION: 1.3.13

    steps:
      - run:
          name: create dist zip file
          command: sbt dist
      - run:
          name: unzip dist zip file
          command: unzip target/universal/mazesite-1.0-SNAPSHOT.zip
      - aws-ecr/build-and-push-image:
          aws-access-key-id: ACCESS_KEY_ID_IAM_ADMIN
          aws-secret-access-key: SECRET_ACCESS_KEY_IAM_ADMIN
          profile-name: IAMAdmin
          region: AWS_REGION_ENV_VAR_NAME
          repo: mazegen

workflows:
  build_and_push_image:
    jobs:
      - build
      - create_and_push_img:
        filters:
          branches:
            only:
              - master



